# Generated by Django 3.0.4 on 2020-04-02 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='KModel',
            fields=[
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=256, null=True)),
                ('notes', models.TextField()),
                ('epochs_trained', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('val_loss', models.IntegerField(null=True)),
                ('tags', models.ManyToManyField(related_name='models', to='mod_man.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=256, null=True)),
                ('notes', models.TextField()),
                ('descriptor', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='mod_man.KModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
